# Generated by Django 3.2.5 on 2021-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210703_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='Saved',
        ),
        migrations.AddField(
            model_name='person',
            name='Saved',
            field=models.ManyToManyField(to='API.SavedURL'),
        ),
    ]
