# Generated by Django 3.2.5 on 2021-07-03 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0003_auto_20210703_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedurl',
            name='Users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedurl',
            name='url',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
