# Generated by Django 3.2.5 on 2021-08-06 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0009_alter_likes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='Users',
        ),
        migrations.AddField(
            model_name='category',
            name='Likes',
            field=models.ManyToManyField(to='API.Likes'),
        ),
        migrations.AddField(
            model_name='category',
            name='Users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='feeds',
            field=models.ManyToManyField(to='API.Feed'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
