# Generated by Django 3.2.5 on 2021-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20210806_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Users',
        ),
        migrations.RemoveField(
            model_name='category',
            name='feeds',
        ),
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.ManyToManyField(to='API.Category'),
        ),
    ]
