# Generated by Django 3.2.5 on 2021-08-06 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0011_auto_20210806_0916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Reader',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Likes',
        ),
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(to='API.Reader'),
        ),
    ]
