# Generated by Django 3.2.5 on 2021-08-10 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0012_auto_20210806_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='category',
        ),
        migrations.AddField(
            model_name='feed',
            name='Category',
            field=models.CharField(default='General', max_length=30),
        ),
        migrations.AddField(
            model_name='feed',
            name='Users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
