# Generated by Django 3.2.5 on 2021-08-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_feed_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='Like',
            field=models.IntegerField(default=0),
        ),
    ]
