# Generated by Django 3.2.5 on 2021-08-10 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0015_alter_feed_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='Like',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('Users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('feeds', models.ManyToManyField(to='API.Feed')),
            ],
        ),
    ]
