# Generated by Django 3.2.5 on 2021-08-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_auto_20210810_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Users',
        ),
    ]
