# Generated by Django 3.2.5 on 2021-08-10 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0018_remove_feed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Users',
        ),
        migrations.RemoveField(
            model_name='category',
            name='feeds',
        ),
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='API.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
